### ISSUE TITLE
Chaos - Legiones Daemonica: Zarakynel missing statline

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-apocalypse#117]
**File:** Chaos - Legiones Daemonica.catz

**BattleScribe version:** 2.03.09

**Platform:** Android

**Dropbox:** No

**Description:** Zarakynel stats are not showing. Her weapons and rules are showing but stats like movement, BS, WS, attacks, etc are not. 

I tried to add her using the superheavy and superheavy auxiliary detachment and found the same issue.

My battlescribe is up to date and I'm using the most up to date  10/29 version of the 40k apocalypse dataset

**Comment by Mad-Spy** [comment]
Some idiot forgot to enter it when he set her up. Fixed now.

**Comment by mustafa2182** [comment]
Hi,

I am still experiencing this issue on Android. I'm the same user as above. I'm using the 1.1.0 version of the Apocalupse datasheet. Is this the reason? The change will be merged onto the live version when the whole thing gets an update?
